# Generated by Django 5.0 on 2023-12-31 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_product_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="Customer",
            new_name="customer",
        ),
    ]
